server.port=8081
spring.application.name=JobSearchApp
spring.jpa.properties.hibernate.dialect=MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/job_search_app
spring.datasource.username=root
spring.datasource.password=zajeciajava123!
spring.jpa.hibernate.ddl-auto=none
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=7cc44ef225084b
spring.mail.password=d7fc4f0daec4c0
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true